apiVersion: 1

datasources:
  - name: Prometheus
    uid: koyalai_prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.53.0
      timeInterval: "15s"
      incrementalQuerying: true
      cacheLevel: Low